name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number'     
        required: true
        type: string

jobs:
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Set Version
        uses: datamonsters/replace-action@v2
        with:
          files: 'pom.xml'
          replacements: 'Snapshot=${{ github.event.inputs.version_number }}'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Rename jar
        run: mv target/*-All.jar JMusicBot-${{ github.event.inputs.version_number }}.jar
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build --build-arg version=${{ github.event.inputs.version_number }} -t $REPO:latest -t $REPO:${GITHUB_SHA::8} -t $REPO:${{ github.event.inputs.version_number }} .
      - name: Publish Docker image
        run: docker push $REPO
